# 端口
server:
  port: 8888

spring:
  application:
    name: isoftstone-security
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.27.223.34:3307/zju_project2?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=CTT
    # url: jdbc:mysql://localhost:3306/zju_project2?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=CTT
    username: root
    password: root
#    password: weng13515774733
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapUnderscoreToCamelCase: true

file:
  path: /src/main/resources/file/

