# 端口
server:
  port: 8888

spring:
  application:
    name: project-manage-server
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.27.223.34:3307/zju_project2?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=CTT
    username: root
    password: root
    # url: jdbc:mysql://localhost:3306/zju_project2?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=CTT
    # password: weng13515774733
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  servlet:
    multipart:
      max-file-size: 100MB # 最大支持文件大小
      max-request-size: 100MB # 最大支持请求大小

mybatis:
  mapper-locations: classpath:mapper/*.xml

file:
  path: 120.27.223.34:8888/


#分布式文件系统Fdfsdfs配置
fdfs:
  soTimeout: 1500 #socket连接超时时长
  connectTimeout: 600 #连接tracker服务器超时时长
  thumbImage: #缩略图生成参数，可选
    width: 150
    height: 150
  trackerList: #TrackerList参数,支持多个，我这里只有一个，如果有多个在下方加- x.x.x.x:port
    - 120.27.223.34:22122
